---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: {{ template "fullname" . }}
    annotations:
      configmap.fabric8.io/update-on-change: jenkins
      fabric8.io/target-platform: kubernetes
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
        provider: fabric8
        group: io.fabric8.tenant.apps
    template:
      metadata:
        annotations:
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/var/jenkins_home"],"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}]'
          configmap.fabric8.io/update-on-change: jenkins
          fabric8.io/target-platform: kubernetes
        labels:
          app: {{ template "fullname" . }}
          provider: fabric8
          version: 4.0.27
          group: io.fabric8.tenant.apps
      spec:
        containers:
        - env:
          - name: PROJECT_NAMESPACE
            value: ${PROJECT_NAMESPACE}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: KUBERNETES_MASTER
            value: {{ .Values.kubernetes.host }}
          - name: MAX_METASPACE_SIZE
            value: 200m
          - name: KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                key: keycloak.url
                name: jenkins
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client.secret
                name: jenkins
          - name: JENKINS_OPTS
            value: -Dgroovy.use.classvalue=true
          - name: JAVA_HOME
            value: /etc/alternatives/java_sdk
          - name: MAVEN_OPTS
            value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          - name: RECOMMENDER_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: jenkins-recommender-api-token
          image: "{{ .Values.jenkins.image.name }}:{{ .Values.jenkins.image.tag }}"
          imagePullPolicy: {{ .Values.jenkins.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - /var/lib/jenkins/pre-shutdown.sh
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            timeoutSeconds: 10
          name: {{ .Chart.Name }}
          ports:
          - containerPort: 50000
            name: slave
          - containerPort: 8080
            name: http
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
            requests:
              memory: 3Gi
              cpu: "1"
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
            readOnly: false
          - mountPath: /usr/local/bin/configuration/
            name: jenkins-config
        serviceAccountName: jenkins
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - configMap:
            name: jenkins
          name: jenkins-config
