---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-home
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    volumeName: jenkins-workspace-efs-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-mvn-local-repo
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    volumeName: jenkins-mvn-local-repo-efs-pv