---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      fabric8.io/target-platform: kubernetes
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins
  data:
    client.secret: Yjc4NzNmODAtNmFkNy00NGE1LTk3Y2ItYmQyMTA3ODllYjQx
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-docker-cfg
  data:
    config.json: ""
  type: fabric8.io/jenkins-docker-cfg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-git-ssh
  data:
    ssh-key: {{ .Values.jenkins.secrets.git.sshKey | quote }}
    ssh-key.pub: {{ .Values.jenkins.secrets.git.sshKeyPub | quote }}
  type: fabric8.io/jenkins-git-ssh
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-hub-api-token
  data:
    hub: ""
  type: fabric8.io/jenkins-hub-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-maven-settings
  data:
    settings.xml: {{ .Values.jenkins.secrets.maven.settings }}
  type: fabric8.io/secret-maven-settings
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-recommender-api-token
  data:
    token: ""
  type: fabric8.io/jenkins-recommender-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-release-gpg
  data:
    trustdb.gpg: {{ .Values.jenkins.secrets.gpg.trustdb | quote }}
    pubring.gpg: {{ .Values.jenkins.secrets.gpg.pubring | quote }}
    gpg.conf: {{ .Values.jenkins.secrets.gpg.conf | quote }}
    secring.gpg: {{ .Values.jenkins.secrets.gpg.secring | quote }}
  type: fabric8.io/jenkins-release-gpg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-ssh-config
  data:
    config: {{ .Values.jenkins.secrets.ssh.config | quote }}
  type: fabric8.io/jenkins-ssh-config
