---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  data:
    # We need to check what this is
    client.secret: Yjc4NzNmODAtNmFkNy00NGE1LTk3Y2ItYmQyMTA3ODllYjQx
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-docker-cfg
  data:
    config.json: {{ .Values.jenkins.secrets.docker.config | quote }}
  type: fabric8.io/jenkins-docker-cfg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-git-ssh
  data:
    ssh-key: {{ .Values.jenkins.secrets.git.sshKey | quote }}
    ssh-key.pub: {{ .Values.jenkins.secrets.git.sshKeyPub | quote }}
  type: fabric8.io/jenkins-git-ssh
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-hub-api-token
  data:
    hub: {{ .Values.jenkins.secrets.git.hubApiToken | quote }}
  type: fabric8.io/jenkins-hub-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-maven-settings
  data:
    settings.xml: {{ .Values.jenkins.secrets.maven.settings }}
  type: fabric8.io/secret-maven-settings
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-recommender-api-token
  data:
    token: ""
  type: fabric8.io/jenkins-recommender-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-release-gpg
  data:
    trustdb.gpg: {{ .Values.jenkins.secrets.gpg.trustdb | quote }}
    pubring.gpg: {{ .Values.jenkins.secrets.gpg.pubring | quote }}
    gpg.conf: {{ .Values.jenkins.secrets.gpg.conf | quote }}
    secring.gpg: {{ .Values.jenkins.secrets.gpg.secring | quote }}
  type: fabric8.io/jenkins-release-gpg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: jenkins-ssh-config
  data:
    config: {{ .Values.jenkins.secrets.ssh.config | quote }}
  type: fabric8.io/jenkins-ssh-config
- apiVersion: v1
  data:
    .dockercfg: {{ .Values.jenkins.secrets.docker.legacyConfig | quote }}
  kind: Secret
  metadata:
    name: docker-registry-secret
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
  type: kubernetes.io/dockercfg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: k8s-external-cluster-kubeconfig
  data:
    config: {{ .Values.jenkins.secrets.kubernetes.externalConfig | quote }}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: k8s-current-cluster-kubeconfig
  data:
    config: {{ .Values.jenkins.secrets.kubernetes.currentConfig | quote }}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: ingress-monitor-controller-test-config
  data:
    config.yaml: {{ .Values.jenkins.secrets.ingressMonitorController.testConfig | quote }}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: chartmuseum-auth
  data:
    username: {{ .Values.jenkins.secrets.chartmuseum.username | quote }}
    password: {{ .Values.jenkins.secrets.chartmuseum.password | quote }}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: slack-notification-hook
  data:
    channel: {{ .Values.jenkins.secrets.slack.channel | quote }}
    webHookURL: {{ .Values.jenkins.secrets.slack.webHookURL | quote }}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: stk-config
  data:
    issuesAuth.yaml: {{ .Values.jenkins.secrets.stk.issuesAuth | quote }}


- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: "helm-pgp-key"
  data:    
{{- with .Values.jenkins.secrets }}    
  {{- range $key, $value := .helmKeys }}
    {{ $key }}: {{ $value }}
  {{- end }}    
{{- end }}