---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}-jnlp
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
{{ include "labels.selector" . | indent 6 }}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/force-ssl-redirect: {{ .Values.jenkins.service.forceSslRedirect }}
        kubernetes.io/ingress.class: {{ .Values.jenkins.service.ingressClass }}
        ingress.kubernetes.io/proxy-body-size: 150m
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
{{ include "labels.selector" . | indent 6 }}