---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}-jnlp
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
{{ include "labels.selector" . | indent 6 }}
- apiVersion: v1
  kind: Service
  metadata:
{{- if .Values.jenkins.service.annotations }}
    annotations:
{{ toYaml .Values.jenkins.service.annotations | indent 6 }}
{{- end }}
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
      expose: "{{ .Values.jenkins.service.expose }}"
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
{{ include "labels.selector" . | indent 6 }}