---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 0f449469a780cab67c0ebba0d725ce060dc61c17
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-services/tenant-jenkins.git/tenant-jenkins-apps/jenkins
      fabric8.io/scm-url: http://github.com/fabric8-services/tenant-jenkins/tenant-jenkins-apps/jenkins
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8-services/tenant-jenkins/tenant-jenkins-apps/jenkins/master/apps/jenkins/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v4.0.27
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-services/tenant-jenkins.git/tenant-jenkins-apps/jenkins
      fabric8.io/scm-tag: fabric8-services/tenant-jenkins-1.0.0
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      expose: "false"
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-jnlp
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: {{ template "fullname" . }}
      provider: fabric8
      group: io.fabric8.tenant.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 0f449469a780cab67c0ebba0d725ce060dc61c17
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-services/tenant-jenkins.git/tenant-jenkins-apps/jenkins
      fabric8.io/scm-url: http://github.com/fabric8-services/tenant-jenkins/tenant-jenkins-apps/jenkins
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8-services/tenant-jenkins/tenant-jenkins-apps/jenkins/master/apps/jenkins/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v4.0.27
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-services/tenant-jenkins.git/tenant-jenkins-apps/jenkins
      fabric8.io/scm-tag: fabric8-services/tenant-jenkins-1.0.0
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/force-ssl-redirect: true
        kubernetes.io/ingress.class: internal-ingress
        ingress.kubernetes.io/proxy-body-size: 150m
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      expose: "true"
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "fullname" . }}
      provider: fabric8
      group: io.fabric8.tenant.apps
