---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      expose: "false"
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins-jnlp
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: {{ template "fullname" . }}
      provider: fabric8
      group: io.fabric8.tenant.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/force-ssl-redirect: true
        kubernetes.io/ingress.class: {{ .Values.jenkins.service.ingressClass }}
        ingress.kubernetes.io/proxy-body-size: 150m
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      provider: fabric8
      expose: "true"
      version: 4.0.27
      group: io.fabric8.tenant.apps
    name: jenkins
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "fullname" . }}
      provider: fabric8
      group: io.fabric8.tenant.apps
