kubernetes:
  host: https://kubernetes.default:443

jenkins:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 2.95
  namespace: default
  externalDockerRegistryURL: ""
  image:
    name: stakater/jenkins-kubernetes
    tag: 2.95
    pullPolicy: IfNotPresent
  secrets:
    git:
      sshKey: ""
      sshKeyPub: ""
      hubApiToken: ""
    maven:
      settings: ""
    gpg:
      trustdb: ""
      pubring: ""
      conf: ""
      secring: ""
    ssh:
      config: ""
    docker:
      config: ""
      legacyConfig: ""
    kubernetes:
      externalConfig: ""
      currentConfig: ""
    ingressMonitorController:
      testConfig: ""
    chartmuseum:
      username: ""
      password: ""
    slack:
      channel: ""
      webHookURL: ""
    stk:
      issuesAuth: ""
  service:
    ingressClass: internal-ingress
  persistence:
    enabled: true
    volumeClaimName: jenkins-home
