kubernetes:
  host: https://kubernetes.default:443

jenkins:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 2.95
  namespace: default
  externalDockerRegistryURL: ""
  annotations:
    configmapReloader: fabric8-pipelines,jenkins
    secretReloader: jenkins,jenkins-docker-cfg,jenkins-git-ssh,jenkins-hub-api-token,jenkins-maven-settings,jenkins-recommender-api-token,jenkins-release-gpg,jenkins-ssh-config,docker-registry-secret,k8s-external-cluster-kubeconfig,k8s-current-cluster-kubeconfig,ingress-monitor-controller-test-config,chartmuseum-auth,slack-notification-hook,stk-config,helm-pgp-key
  image:
    name: stakater/jenkins-kubernetes
    tag: 2.95
    pullPolicy: IfNotPresent
  security:
    enabled: true
    realm: |-
        <securityRealm class="org.jenkinsci.plugins.oic.OicSecurityRealm" plugin="oic-auth@1.0">
          <clientId>fabric8-online-platform</clientId>
          <clientSecret>${KEYCLOAK_CLIENT_SECRET}</clientSecret>
          <tokenServerUrl>${KEYCLOAK_URL}/auth/realms/fabric8/protocol/openid-connect/token</tokenServerUrl>
          <authorizationServerUrl>${KEYCLOAK_URL}/auth/realms/fabric8/protocol/openid-connect/auth</authorizationServerUrl>
          <userNameField>email</userNameField>
          <scopes>openid email</scopes>
        </securityRealm>
  secrets:
    helmKeys:      
      stakater.asc: "your-public-pgp-key"
    git:
      sshKey: ""
      sshKeyPub: ""
      hubApiToken: ""
      gitlabToken: ""
    maven:
      settings: ""
    gpg:
      trustdb: ""
      pubring: ""
      conf: ""
      secring: ""
    ssh:
      config: ""
    docker:
      config: ""
      legacyConfig: ""
    kubernetes:
      externalConfig: ""
      currentConfig: ""
    ingressMonitorController:
      testConfig: ""
    chartmuseum:
      username: ""
      password: ""
    slack:
      channel: ""
      webHookURL: ""
    stk:
      issuesAuth: ""
  service:
    ingressClass: internal-ingress
    forceSslRedirect: "true"
    expose: "true"
  persistence:
    enabled: true
    volumeClaimName: jenkins-home
  
  forecastle: {}
    # icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
    # expose: "true"